MusicSEC/Models/CUserImage.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : CUserImages
// Abstract : Database Model for CUserImages
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.IO;
using MusicSEC.Utility;

namespace MusicSEC.Models
{
    public class CUserImage
    {
        public int CUserImageID { get; set; }
       
        public string strCaption { get; set; }
        public string strFileType { get; set; }
        public bool blnCaptionTop { get; set; }
        public byte[] bytImage { get; set; }

        public CUserImage ProcessBytes(HttpPostedFileBase file)
        {
            var image = new CUserImage();
            var extension = Path.GetFileName(file.FileName);

            if (extension != null)
                image.strFileType = extension.TrimStart('.');

            image.bytImage = file.ConvertImageToBytes();

            return image;
        }

        public byte[] ImageToBytes(HttpPostedFileBase file)
        {
            return file.ConvertImageToBytes();
        }

        public string GetFileName(HttpPostedFileBase file)
        {
            var extension = Path.GetFileName(file.FileName);
            if (extension != null)
                return extension.TrimStart('.');
            else
                return "";
        }

    }
}

MusicSEC/Controllers/CUserImagesController.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : CUserImageController
// Abstract : Controller for User Images
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicSEC.DAL;
using MusicSEC.Models;

namespace MusicSEC.Controllers
{
    public class CUserImagesController : Controller
    {
        CUnitOfWork unit = new CUnitOfWork();
        //
        // GET: /CUserImages/
        //--------------------------------------------------------------
        // Name : DisplayPictureGrid
        // Abstract : return a grid of all pictures
        //--------------------------------------------------------------
        public ActionResult DisplayPictureGrid()
        {
            var images = unit.ImageRep.GetAll().ToList();
            return PartialView(images);
        }

        //--------------------------------------------------------------
        // Name : UploadImage
        // Abstract : users upload image view save
        //--------------------------------------------------------------
        public ActionResult UploadImage(bool enableCaptions = false, bool enableButtonPane = true)
        {
            var userImage = new CUserImage();
            ViewBag.EnableCaptions = enableCaptions;
            ViewBag.EnableButtonPane = enableButtonPane;
            return PartialView(userImage);
        }

        //--------------------------------------------------------------
        // Name : UploadImage
        // Abstract : users upload image view save
        //--------------------------------------------------------------
        [HttpPost]
        public ActionResult UploadImage(CUserImage image, FormCollection collection)
        {
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase file = Request.Files[0];
                image.strFileType = image.GetFileName(file);
                image.bytImage = image.ImageToBytes(file);
                unit.ImageRep.Insert(image);
                unit.Save();
            }

            return RedirectToAction("ManageImages");
        }

        //--------------------------------------------------------------
        // Name : ManageImages
        // Abstract : manage user image vies
        //--------------------------------------------------------------
        public ActionResult ManageImages()
        {
            var lstImages = unit.ImageRep.GetAll().ToList();
            return PartialView(lstImages);
        }

        //--------------------------------------------------------------
        // Name : DeleteImage
        // Abstract : remove image
        //--------------------------------------------------------------
        [HttpPost]
        public void DeleteImage(int imageId)
        {
            var image = unit.ImageRep.FindById(imageId);
            var instructor = unit.InstructorRep.GetAll(x => x.CUserImageID == imageId).FirstOrDefault();

            if (instructor != null)
            {
                instructor.CUserImageID = null;
                unit.InstructorRep.Update(instructor);
            }

            if (image != null)
            {
                unit.ImageRep.Remove(image);
                unit.Save();
            }
        }

        //--------------------------------------------------------------
        // Name : getImageInfo
        // Abstract : get image information
        //--------------------------------------------------------------
        public string getImageInfo(int imageId)
        {
            return unit.ImageRep.GetAll(x => x.CUserImageID == imageId).Select(x => x.strFileType).FirstOrDefault();
        }
    }

   
}

MusicSEC/Views/CUserImages/DisplayPictureGrid.cshtml
@model List<MusicSEC.Models.CUserImage>

<div class="picture-grid-container">
    <ul id="ImageList">
    @foreach (var item in Model)
    {
        <li data-id="@item.CUserImageID">
            @Html.DisplayFor(model => item) 
        </li>
     }
    </ul>
</div>
<script>
    var imagelistLi = $('#ImageList li');
    var currentImageId = 0;

    imagelistLi.click(function () {
        currentImageId = $(this).data('id');
    });

    function getCurrentImageId() {
        return currentImageId;
    };
</script>

MusicSEC/Views/CUserImages/ManageImages.cshtml
@model IEnumerable<MusicSEC.Models.CUserImage>

<div class="msc-dsp-row">
    <div class="msc-dsp-cell">
        @{Html.RenderAction("UploadImage", new { enableCaptions = true });}
    </div>
    <div class="msc-dsp-cell">
        <ul id="ImageList">
            @foreach (var item in Model)
            {
                <li data-id="@item.CUserImageID">
                    <div>
                        @Html.DisplayFor(model => item)
                        <input type="button" name="btnRemove" value="Remove Image" />
                    </div>
                </li>         
            }
        </ul>
    </div>
</div>
<script>
    var imageListLi = $('#ImageList li');
    var selectedImageId = 0;

    toggleRemoveButton();

    imageListLi.click(function () {
        selectedImageId = $(this).data('id');
        toggleRemoveButton();
    });

    $('input[name=btnRemove]').click(function () {
        $.post('@Url.Action("DeleteImage")', { imageId : selectedImageId }, function () {
            removeImage();
        });
    });

    function toggleRemoveButton() {
        $.each(imageListLi, function (index, li) {
            var li = $(li);
            if (li.data('id') == selectedImageId) {
                li.find('input[name=btnRemove]').css('display', 'block');
            }
            else {
                li.find('input[name=btnRemove]').css('display', 'none');
            }
        });
    };

    function removeImage() {
        $.each(imageListLi, function (index, li) {
            var li = $(li);
            if (li.data('id') == selectedImageId) {
                li.remove();
            }
        });
    };
</script>

MusicSEC/Views/CUserImages/UploadImage.cshtml
@model MusicSEC.Models.CUserImage

@{
    ViewBag.Title = "UploadImage";
    bool blnEnableCaptions = ViewBag.EnableCaptions;
    bool blnEnableButtonPane = ViewBag.EnableButtonPane;
}

@using(Html.BeginForm("UploadImage", "CUserImages", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true);
<div class="msc-image-upload-container">
    
    @if (blnEnableCaptions)
    {
        <span>
            <label class="msc-label-for">Caption position:</label>
            <input type="radio" id="rdTop" value="top" name="rdCaptionPos" />
            <label class="msc-label-for">Top</label>
            <input type="radio" id="rdBottom" value="bottom" name="rdCaptionPos" checked="checked"/>
            <label class="msc-label-for">Bottom</label>
        </span>
    }
    @if (blnEnableCaptions)
    {
        <input type="text" id="topCaption" class="msc-caption" style="width:240px;"/>
    }
    <img src="~/Content/images/no_photo_icon.png"  id="imgUploadPreview" class="msc-profile-lg msc-block" style="max-height:225px;"/>
    @if (blnEnableCaptions)
    {
        <input type="text" id="bottomCaption" class="msc-caption" style="width:240px;"/>
    }
    <input type="file" name="fileUpload" id="fileUpload" accept="image/*" onchange="previewImage();" style="width:240px;" />
    @if(blnEnableButtonPane)
    {
        <span class="msc-button-pane">
            <input type="submit" value="Upload"  />
           @* <input type="button" value="Cancel"  />*@
        </span>
    }
    <input type="hidden" name="blnCaptionTop" />
    <input type="hidden" name="strCaption" />
</div>
}
<script src="~/Scripts/instructor-crud.js"></script>
<script>
    var radios = $("input[name=rdCaptionPos]");
    var topCaption = $("#topCaption");
    var bottomCaption = $("#bottomCaption");
    var hdnCaptionTop = $("input[name=blnCaptionTop]");
    var hdnCaption = $("input[name=strCaption]");
    setCaptionVisible();
    
    radios.change(setCaptionVisible);
    topCaption.change(setCaption);
    bottomCaption.change(setCaption);

    function setCaptionVisible() {
        if ($("input[name=rdCaptionPos]:checked").val() == "bottom") {
            topCaption.hide();
            topCaption.val("");
            bottomCaption.show();
            hdnCaptionTop.val(false);
        }
        else {
            topCaption.show();
            bottomCaption.hide();
            bottomCaption.val("");
            hdnCaptionTop.val(true);

        }
        setCaption();
    };

    function setCaption() {
        var caption = (hdnCaptionTop.val() == "true") ? topCaption.val() : bottomCaption.val();
        hdnCaption.val(caption);
    };
</script>