MusicSEC/Controllers/StatController.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : StatController
// Abstract : Controller for Academy Statistics
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicSEC.DAL;
using MusicSEC.Utility;
using MusicSEC.ViewModels;

namespace MusicSEC.Controllers
{
    public class StatController : Controller
    {
        CUnitOfWork unit = new CUnitOfWork();

        //--------------------------------------------------------------
        // Name : AcademyStat
        // Abstract : the academy stat view
        //--------------------------------------------------------------
        public ActionResult AcademyStat(AcademyStatVM vm = null, int statusId = 1, int orderId = 1, string lastTab = "fs-tab-1")
        {
            if (vm.dtmStartDate.Year < 1988)
            {
                vm.dtmStartDate = DateTime.Now.AddDays(-7).Date;
            }
            if (vm.dtmEndDate.Year < 1988)
            {
                vm.dtmEndDate = DateTime.Now.AddDays(7).Date;
            }

            var academyStat = new AcademyStatVM(vm.dtmStartDate, vm.dtmEndDate).MapViewModel(unit);
            var dctsStatus = CLessonUtility.Instance.LessonStatus();
            var dctLessonOrder = CLessonUtility.Instance.LessonOrder();
            ViewBag.ddlStatus = new SelectList(dctsStatus, "key", "value", statusId);
            ViewBag.ddlLessonOrder = new SelectList(dctLessonOrder, "key", "value", orderId);
            ViewBag.LastTab = lastTab;
            return PartialView(academyStat);
        }

        //--------------------------------------------------------------
        // Name : InstructorByLessonStatus
        // Abstract : return instructor name for lesson status filter criteria
        //--------------------------------------------------------------
        public string InstructorByLessonStatus(int statusId, int lessonOrder, DateTime start, DateTime end)
        {
            bool blnLessonOrder = (lessonOrder == 1) ? true :false;
            int intInstructorId = CLessonUtility.Instance.StatByStatus(unit, statusId, blnLessonOrder, start, end);
            string strFullName = unit.InstructorRep.GetAll(x => x.CInstructorID == intInstructorId).
                                                    Select(x => x.strFirstName + " " + x.strLastName).
                                                    FirstOrDefault() ?? "";
            return (strFullName == "") ? "no result" : strFullName;
        }


        
    }
}

MusicSEC/Views/Stat/AcademyStat.cshtml
@model MusicSEC.ViewModels.AcademyStatVM
<style>
    #spDate, #spRange {
        display:inline-block;
        width:175px;
    }

    #spDate {
        margin-left:10%;
    }

    .msc-stat-container {
        width:85%;
        height:400px;
        overflow-y:auto;
        margin:auto;
    }

    .msc-stat-container label {
        display:inline-block;
        width:210px;
    }

    .msc-stat-container select {
        width:160px;
    }
  
    .msc-short-txt {
        width:150px;
    }

    .msc-mdm-txt {
        width:175px;
    }

    .msc-stat-dtm {
        display:block;
        margin:5px auto;
        width:70%;
        height:50px;
        border-radius:12px;
        border:2px inset black;
        background-color:rgba(0,0,0,.3);
    }

    .msc-stat-dtm button {
        float:left;
        margin:0px;
    }

    .msc-stat-dtm input[type=text] {
        width:125px;
        margin-top:0px;
        margin-left:3px;
        background:none;
        border:none;
        color:white;
    }

    .tab-container {
        width:90%;
        height:260px;
        padding:15px;
        border:2px inset black;
        border-top:1px solid black;
        border-bottom-left-radius:20px;
        border-bottom-right-radius:20px;
        border-top-right-radius:20px;
    }

    .tab-holder {
        display:block;
        width:90%;
    }

        .tab-holder label {
            width:150px;
            height:30px;
            border:2px inset black;
            border-bottom-color:rgba(0, 0, 0, .7);
            border-bottom:2px;
            text-align:center;
        }
    #fs-tab-1 {
        border-top-left-radius:12px;
        border-right:1px inset black;
    }

    #fs-tab-2{
     /*   border-top-right-radius:12px;*/
        border-left:1px inset black;
        border-right:1px inset black;
    }

    #fs-tab-3 {
        border-left:1px inset black;
        border-right:1px inset black;
     }

     #fs-tab-4 {
        border-top-right-radius:12px;
        border-left:1px inset black;
     }

    .fs-selected {
        background-color:rgba(0, 0, 0, .7)
    }
    .fs-tab-selected {
        background-color:rgba(178, 223, 254, .2);
    }

    .msc-fs-scrollable {
        height:250px;
        overflow-y:auto;
    }

</style>
@using(Html.BeginForm("AcademyStat", "Stat"))
{
<div class="msc-stat-container">
      <!--Date-->
        <div class="hdn-fs">
            <span class="msc-stat-dtm">
                <span id="spDate">
                    <input type="text" name="dtmStartDate" value="@Model.dtmStartDate.ToShortDateString()" class="msc-short-txt" />
                </span>
                <span id="spRange">
                    <input type="text" name="dtmEndDate" value="@Model.dtmEndDate.ToShortDateString()" class="msc-short-txt" /> 
                </span>
                <input type="submit" value="Search" />
            </span>
        </div>   
        <div class="tab-holder">
            <label id="fs-tab-1" class="fs-tab">Instructors</label>
            <label id="fs-tab-2" class="fs-tab">Students</label>
            <label id="fs-tab-3" class="fs-tab">Lessons</label>
            <label id="fs-tab-4" class="fs-tab">Studios</label>
        </div>
        <div class="tab-container fs-selected">
        <div id="hdn-fs-1">
            <table>
                <tr>
                    <th>Instructor Name</th>
                    <th>Lesson Status</th>
                    <th>Lesson Order</th>
                </tr>
                <tr>
                   <td><input type="text" name="txtInstructorName" class="msc-mdm-txt"/></td>
                   <td>@Html.DropDownList("ddlStatus", (SelectList)ViewBag.Status)</td>
                   <td>@Html.DropDownList("ddlLessonOrder", (SelectList)ViewBag.Most)</td>
                </tr>
            </table>
            <span>
                @Html.Label("Active Instructor Count")
                @Html.TextBoxFor(model => model.intActiveInstructorCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
            <br />
            <span>
                @Html.Label("Inactive Instructor Count")
                @Html.TextBoxFor(model => model.intInActiveInstructorCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
        </div>
 

    <!--Student-->
   
        
        <div id="hdn-fs-2">
            <span>
                @Html.Label("Active Student Count")
                @Html.TextBoxFor(model => model.intActiveStudentCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
            <br />
            <span>
                @Html.Label("Inactive Student Count")
                @Html.TextBoxFor(model => model.intInActiveStudentCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
        </div>

    <!--Lessons-->
            <div id="hdn-fs-3">
                <div class="msc-fs-scrollable">
                <table>
                    <tr>
                        <th>Date</th>
                        <th>Instructor</th>
                        <th>Student</th>
                        <th>Studio</th>
                        <th>Start Time</th>
                        <th>Status</th>
                        <th>Notes</th>
                    </tr>
                    @foreach (var item in Model.lstLessons)
                    {
                        <tr>
                            <td>@item.dtmDate.ToShortDateString()</td>
                            <td>@item.strInstructorName</td>
                            <td>@item.strStudentName</td>
                            <td>@item.strStudioName</td>
                            <td>@item.ConvertStartTime</td>
                            <td>@item.GetStatus</td>
                            <td><img class="mcs-notes-img" src="~/Content/images/home_note.png" title="@item.strComments" style="width:30px;height:30px;background-color:white;display:inline-block;vertical-align:middle;margin-right:3px;"/></td>
                        </tr> 
                    }
                </table>
                </div>
            </div>
            <!--Studios-->
            <div id="hdn-fs-4">
                <table>
                    <tr>
                        <th>Studio</th>
                        <th>Actual Lessons</th>
                        <th>Total Lessons</th>
                        <th>Percentage Used</th>
                    </tr>
                    @foreach (var pair in Model.DctStudioHelpers)
                    {
                        <tr>
                            <td>@pair.Key</td>
                            <td>@pair.Value.intNumberOfLessons</td>
                            <td>@pair.Value.intTotalLessons</td>
                            <td>@pair.Value.dcmPercentUsed.ToString("P2")</td>
                        </tr> 
                    }
                </table>
            </div>
    </div>
    <input type="hidden" name="statusId" />
    <input type="hidden" name="orderId" />
    <input type="hidden" name="lastTab" value="@ViewBag.LastTab" />
</div>
}
<script>
    var dtmStart = $('input[name=dtmStartDate]');
    var dtmEnd = $('input[name=dtmEndDate]');
    var statusSelect = $('select[name=ddlStatus]');
    var orderSelect = $('select[name=ddlLessonOrder]');
    var txtInstructorName = $('input[name=txtInstructorName]');
    var status = $('input[name=statusId]');
    var order = $('input[name=orderId]');
    var tab = $('.fs-tab');
    var tabIndex1 = $('#fs-tab-1');
    var tabIndex2 = $('#fs-tab-2');
    var tabIndex3 = $('#fs-tab-3');
    var tabIndex4 = $('#fs-tab-4');
    var tab1 = $('#hdn-fs-1');
    var tab2 = $('#hdn-fs-2');
    var tab3 = $('#hdn-fs-3');
    var tab4 = $('#hdn-fs-4');
    var lastTab = $('input[name=lastTab]');
    //   var currentTabIndex = 'fs-tab-1';
    var currentTabIndex = $('input[name=lastTab]').val();
    

    getInstructor();
    toggleTab(currentTabIndex);
    statusSelect.change(function () {
        getInstructor();
    });

    orderSelect.change(function () {
        getInstructor();
    });

    tab.click(function () {
        toggleTab($(this).attr('id'));
        currentTabIndex = $(this).attr('id');
    });

    tab.hover(function () {
        var tb = $(this);
        
        if (tb.attr('id') != currentTabIndex) {
            tb.toggleClass('fs-tab-selected');
        }
    });

    $(function () {
        dtmStart.datepicker({
            showOn: 'button'
        }).next('button').text('').button({
            icons: {
                primary: 'ui-icon-calendar'
            },
            text: false
        });
    });

    $(function () {
        dtmEnd.datepicker({
            showOn: 'button'
        }).next('button').text('').button({
            icons: {
                primary: 'ui-icon-calendar'
            },
            text: false
        });
    });

    $.each($('.mcs-notes-img'), function (index, img) {
        var img = $(img);
        if (img.attr('title') != '' && img.attr('title') != null) {
            img.css('border', '2px inset lightgreen');
        }
    });

    function getInstructor() {
        var statusId = statusSelect.val();
        var orderId = orderSelect.val();
        if (statusId != null && statusId != "" && orderId != null && orderId != "") {
            $.get('@Url.Action("InstructorByLessonStatus")', { statusId: statusId, lessonOrder: orderId, start: dtmStart.val(), end: dtmEnd.val() }, function (data) {
                txtInstructorName.val(data);
                status.val(statusId);
                order.val(orderId);
            });
        }
    };

    function toggleTab(id) {
        tab.removeClass('fs-selected');
        switch (id) {
            case 'fs-tab-1':
                tab1.show();
                tab2.hide();
                tab3.hide();
                tab4.hide();
                tabIndex1.addClass('fs-selected');
                tabIndex1.removeClass('fs-tab-selected');
                setLastTab('fs-tab-1');
                break;
            case 'fs-tab-2':
                tab1.hide();
                tab2.show();
                tab3.hide();
                tab4.hide();
                tabIndex2.addClass('fs-selected');
                tabIndex2.removeClass('fs-tab-selected');
                setLastTab('fs-tab-2');
                break;
            case 'fs-tab-3':
                tab1.hide();
                tab2.hide();
                tab3.show();
                tab4.hide();
                tabIndex3.addClass('fs-selected');
                tabIndex3.removeClass('fs-tab-selected');
                setLastTab('fs-tab-3');
                break;
            case 'fs-tab-4':
                tab1.hide();
                tab2.hide();
                tab3.hide()
                tab4.show();
                tabIndex4.addClass('fs-selected');
                tabIndex4.removeClass('fs-tab-selected');
                setLastTab('fs-tab-4');
                break;
        }
        
    };

    function setLastTab(tabId) {
        lastTab.val(tabId);
    };
</script>

MusicSEC/Views/Stat/Copy of AcademyStat.cshtml
@model MusicSEC.ViewModels.AcademyStatVM
<style>
    #spDate, #spRange {
        display:inline-block;
        width:175px;
    }

    #spDate {
        margin-left:10%;
    }

    .msc-stat-container {
        width:85%;
        height:400px;
        overflow-y:auto;
        margin:auto;
    }

    .msc-stat-container label {
        display:inline-block;
        width:210px;
    }

    .msc-stat-container select {
        width:160px;
    }
  
    .msc-short-txt {
        width:150px;
    }

    .msc-mdm-txt {
        width:175px;
    }

    .msc-stat-dtm {
        display:block;
        margin:5px auto;
        width:70%;
        height:50px;
        border-radius:12px;
        border:2px inset black;
        background-color:rgba(0,0,0,.3);
    }

    .msc-stat-dtm button {
        float:left;
        margin:0px;
    }

    .msc-stat-dtm input[type=text] {
        width:125px;
        margin-top:0px;
        margin-left:3px;
        background:none;
        border:none;
        color:white;
    }

    .tab-container {
        width:90%;
        height:260px;
        padding:15px;
        border:2px inset black;
        border-top:1px solid black;
        border-bottom-left-radius:20px;
        border-bottom-right-radius:20px;
        border-top-right-radius:20px;
    }

    .tab-holder {
        display:block;
        width:90%;
    }

        .tab-holder label {
            width:150px;
            height:30px;
            border:2px inset black;
            border-bottom-color:rgba(0, 0, 0, .7);
            border-bottom:2px;
            text-align:center;
        }
    #fs-tab-1 {
        border-top-left-radius:12px;
        border-right:1px inset black;
    }

    #fs-tab-2{
        border-top-right-radius:12px;
        border-left:1px inset black;
    }
    .fs-selected {
        background-color:rgba(0, 0, 0, .7)
    }
    .fs-tab-selected {
        background-color:rgba(178, 223, 254, .2);
    }

</style>
@using(Html.BeginForm("AcademyStat", "Stat"))
{
<div class="msc-stat-container">
      <!--Date-->
        <div class="hdn-fs">
            <span class="msc-stat-dtm">
                <span id="spDate">
                    <input type="text" name="dtmStartDate" value="@Model.dtmStartDate.ToShortDateString()" class="msc-short-txt" />
                </span>
                <span id="spRange">
                    <input type="text" name="dtmEndDate" value="@Model.dtmEndDate.ToShortDateString()" class="msc-short-txt" /> 
                </span>
                <input type="submit" value="Search" />
            </span>
        </div>   
        <div class="tab-holder">
            <label id="fs-tab-1" class="fs-tab">Instructors</label>
            <label id="fs-tab-2" class="fs-tab">Students</label>
        </div>
        <div class="tab-container fs-selected">
        <div id="hdn-fs-1">
            <table>
                <tr>
                    <th>Instructor Name</th>
                    <th>Lesson Status</th>
                    <th>Lesson Order</th>
                </tr>
                <tr>
                   <td><input type="text" name="txtInstructorName" class="msc-mdm-txt"/></td>
                   <td>@Html.DropDownList("ddlStatus", (SelectList)ViewBag.Status)</td>
                   <td>@Html.DropDownList("ddlLessonOrder", (SelectList)ViewBag.Most)</td>
                </tr>
            </table>
            <span>
                @Html.Label("Active Instructor Count")
                @Html.TextBoxFor(model => model.intActiveInstructorCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
            <br />
            <span>
                @Html.Label("Inactive Instructor Count")
                @Html.TextBoxFor(model => model.intInActiveInstructorCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
        </div>
 

    <!--Student-->
   
        
        <div id="hdn-fs-2">
            <span>
                @Html.Label("Active Student Count")
                @Html.TextBoxFor(model => model.intActiveStudentCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
            <br />
            <span>
                @Html.Label("Inactive Student Count")
                @Html.TextBoxFor(model => model.intInActiveStudentCnt, new { disabled = "disabled", @readonly = "readonly", @class = "msc-short-txt" })
            </span>
        </div>
    </div>
    <input type="hidden" name="statusId" />
    <input type="hidden" name="orderId" />
</div>
}
<script>
    var dtmStart = $('input[name=dtmStartDate]');
    var dtmEnd = $('input[name=dtmEndDate]');
    var statusSelect = $('select[name=ddlStatus]');
    var orderSelect = $('select[name=ddlLessonOrder]');
    var txtInstructorName = $('input[name=txtInstructorName]');
    var status = $('input[name=statusId]');
    var order = $('input[name=orderId]');
    var tab = $('.fs-tab');
    var tabIndex1 = $('#fs-tab-1');
    var tabIndex2 = $('#fs-tab-2');
    var tab1 = $('#hdn-fs-1');
    var tab2 = $('#hdn-fs-2'); 
    

    getInstructor();
    toggleTab('fs-tab-1');
    statusSelect.change(function () {
        getInstructor();
    });

    orderSelect.change(function () {
        getInstructor();
    });

    tab.click(function () {
        toggleTab($(this).attr('id'));
    });

    tab.hover(function () {
        var tb = $(this);
        if (tab1.is(':visible') && tb.attr('id') == 'fs-tab-2') {
            tb.toggleClass('fs-tab-selected');
        }
        else if (tab2.is(':visible') && tb.attr('id') == 'fs-tab-1') {
            tb.toggleClass('fs-tab-selected');
        }
    });

    $(function () {
        dtmStart.datepicker({
            showOn: 'button'
        }).next('button').text('').button({
            icons: {
                primary: 'ui-icon-calendar'
            },
            text: false
        });
    });

    $(function () {
        dtmEnd.datepicker({
            showOn: 'button'
        }).next('button').text('').button({
            icons: {
                primary: 'ui-icon-calendar'
            },
            text: false
        });
    });

    function getInstructor() {
        var statusId = statusSelect.val();
        var orderId = orderSelect.val();
        if (statusId != null && statusId != "" && orderId != null && orderId != "") {
            $.get('@Url.Action("InstructorByLessonStatus")', { statusId: statusId, lessonOrder: orderId, start: dtmStart.val(), end: dtmEnd.val() }, function (data) {
                txtInstructorName.val(data);
                status.val(statusId);
                order.val(orderId);
            });
        }
    };

    function toggleTab(id) {
        tab.removeClass('fs-selected');
        if (id == 'fs-tab-1') {
            tab1.show();
            tab2.hide();
            tabIndex1.addClass('fs-selected');
            tabIndex1.removeClass('fs-tab-selected');
        }
        else {
            tab1.hide();
            tab2.show();
            tabIndex2.addClass('fs-selected');
            tabIndex2.removeClass('fs-tab-selected');
        }
    };
</script>