MusicSEC/Models/CDay.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class  : CDay
// Abstract : Database Model for Days
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using MusicSEC.Models;

namespace MusicSEC.Models
{
    public class CDay
    {
        public int CDayID { get; set; }
        public DateTime dtmDate { get; set; }
        public int intOperationsStartTime { get; set; } // Minutes since midnight
        public int intOperationsEndTime { get; set; } // Minutes since midnight
        public bool blnOperational { get; set; }

        public virtual ICollection<CStudio> Studios { get; set; }
    }
}

MusicSEC/Controllers/CDayController.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : CDayController
// Abstract : Controller for CDays
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicSEC.DAL;
using MusicSEC.Models;
using MusicSEC.Utility;
using MusicSEC.ViewModels;

namespace MusicSEC.Controllers
{
    public class CDayController : Controller
    {
        private CUnitOfWork unit = new CUnitOfWork();
        //
        // GET: /CDay/

        //--------------------------------------------------------------
        // Name : Details
        // Abstract : return day details view
        //--------------------------------------------------------------
        public ActionResult Details(int day, int month, int year)
        {
            var cday = unit.DayRep.GetAll(x => x.dtmDate.Day == day && 
                                               x.dtmDate.Month == month && 
                                               x.dtmDate.Year == year).
                                               FirstOrDefault();

            var cdayvm = new CDayVM().MapViewModel(cday, unit);
            if (unit.IsAdministrator)
            {
                ViewBag.IsAdmin = true;
                return PartialView("AdminDay", cdayvm);
            }
            else if (unit.IsInstructor)
            {
                ViewBag.IsInstructor = true;
                ViewBag.InstructorId = CUserUtility.Instance.GetCurrentInstructorId(unit);
                return PartialView("InstructorDay", cdayvm);
            }
            else if (unit.IsEnrolled)
            {
                ViewBag.IsEnrolled = true;
                ViewBag.StudentId = CUserUtility.Instance.GetCurrentStudentId(unit);
                return PartialView("StudentDay", cdayvm);
            }
            else
            {
                ViewBag.IsAnonymous = true;
            }

            
            return PartialView(cdayvm);
        }

        //--------------------------------------------------------------
        // Name : Finish
        // Abstract : Finish setting details
        //--------------------------------------------------------------
        public ActionResult Finish()
        {
            bool blnNeedsCompleted = true;

            if (unit.DayRep.GetAll().Count() > 0)
                blnNeedsCompleted = false;   
                
            ViewBag.NeedsCompleted = blnNeedsCompleted;

            return PartialView();
        }

        ///--------------------------------------------------------------
        // Name : GenerateDays
        // Abstract : call seed utility and generate calendar
        //--------------------------------------------------------------
        public ActionResult GenerateDays()
        {
            CSeedUtility.SeedCalendar(unit, DateTime.Now);
            return RedirectToAction("Finish");
        }

        //--------------------------------------------------------------
        // Name : UpdateDayTime
        // Abstract : update operational time for day
        //--------------------------------------------------------------
        [HttpPost]
        public ActionResult UpdateDayTime(CDayVM cdayvm)
        {
            if (cdayvm.CDayID != 0)
            {
                var oplength = cdayvm.OplengthVm;
                bool blnIsAm = (oplength.intStartAm == 0) ? true : false;
                bool blnIsPm = (oplength.intEndAm == 0) ? true : false;
                cdayvm.intStartTime = CTimeUtility.MinutesSinceMidnight(oplength.intStartHours, oplength.intStartMins, blnIsAm);
                cdayvm.intEndTime = CTimeUtility.MinutesSinceMidnight(oplength.intEndHours, oplength.intEndMins, blnIsPm);
                cdayvm.blnOperational = oplength.blnIsOperational;
                var day = cdayvm.MapModel(cdayvm, unit);

                unit.DayRep.Update(day);
                unit.Save();
            }

            return PartialView("Details", new { day = cdayvm.intDay, month = cdayvm.intMonth, year = cdayvm.intYear });
        }

    }
}

MusicSEC/Views/CDay/AdminDay.cshtml
@model MusicSEC.ViewModels.CDayVM
@using MusicSEC.Utility

@using (Ajax.BeginForm("UpdateDayTime", "CDay", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "AdminDay", OnComplete = "setActive" }))
{
<div id="AdminDay">
<div>
    <input type="button" name="btnToggle" value="< Back" />
    <h2>@Model.dtmDate.ToShortDateString()</h2>
    <input type="submit" class="msc-day-submit" value="Update Day" />
    <br />
    <span>
        @Html.Label("Day")
        @Html.Label("Start Time")
        @Html.Label("End Time")
        @Html.Label("Operational")
    </span>
    @Html.EditorFor(model => model.OplengthVm)
   
</div>
<div class="msc-overflow" style="height:225px;">
    @Html.HiddenFor(model => model.CDayID)
    @Html.HiddenFor(model => model.dtmDate)
    @Html.HiddenFor(model => model.intDay)
    @Html.HiddenFor(model => model.intMonth)
    @Html.HiddenFor(model => model.intYear)
    @Html.HiddenFor(model => model.intLessonsPerDay)
 
    <ul>
    @foreach (var studio in Model.lstStudios)
    {
        <li class="admin-day-li">
            @Html.DisplayFor(modelItem => studio.strStudioName)
            <input type="button" name="btnFolded" value="+"/>
            <table class="msc-hidden">
                <tr>
                    <td>@Html.Label("Start Time")</td>
                    <td>@Html.Label("End Time")</td>
                    <td>@Html.Label("Slot Available")</td>
                </tr>
            @foreach (KeyValuePair<int, MusicSEC.ViewModels.CLessonVM> pair in studio.dctLessonSlots)
            {
                 <tr>
                    <td>@CTimeUtility.ConvertToReadable(pair.Value.intStartTime)</td>
                    <td>@CTimeUtility.ConvertToReadable(pair.Value.intEndTime)</td>
                    <td>@pair.Value.blnAvailable.ToString()</td>
                 </tr>
            } 
            </table>
        </li>
    }
    </ul>
</div>
</div>
}
@Scripts.Render("~/bundles/jqueryval")
<script>
    $('input[name=btnFolded]').click(function () {
        var button = $(this);
        var val = (button.val() == '+') ? '-' : '+';
        button.parent().children('table').toggleClass('msc-hidden');
        button.val(val);
    });

    $('input[name=btnToggle]').click(function () {
        toggleDisplay();
    });
</script>

MusicSEC/Views/CDay/Details.cshtml
@model MusicSEC.ViewModels.CDayVM


Operational : @Html.DisplayFor(model => model.blnOperational)
Day : @Html.DisplayFor(model => model.intDay)
Month : @Html.DisplayFor(model => model.intMonth)
Year : @Html.DisplayFor(model => model.intYear)


<ul>
@foreach (var item in Model.lstStudios)
{ 
    <li>@Html.DisplayFor(modelItem => item.strStudioName)</li>
}
</ul>

MusicSEC/Views/CDay/Finish.cshtml
<div class="msc-lesson-type-create">
    <h3>Business Settings Complete</h3>
@if (ViewBag.NeedsCompleted) 
{
    <p class="msc-p">
        You're almost finished.  All that is left is to click create calendar to generate
        a calendar which enable menu items.
    </p>
}
else
{
    <p class="msc-p">
        Business settings are complete. A calendar exists, if you create a new calendar all previous data for the year will be lost.
    </p>
}
</div>
<p class="msc-lesson-type-panel">
    <span>
        @Html.ActionLink("< Back", "Index", "CStudioName")
        @Html.ActionLink("Create New", "GenerateDays", "CDay")
    </span>
</p>

MusicSEC/Views/CDay/InstructorDay.cshtml
@model MusicSEC.ViewModels.CDayVM
@using MusicSEC.ViewModels
<style>
  
</style>

@*@using (Ajax.BeginForm("UpdateDayTime", "CDay", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "AdminDay", OnComplete = "setActive" }))
{
*@
<div id="AdminDay">
<div>
    <input type="button" name="btnToggle" value="< Back" />
    <h2>@Model.dtmDate.ToShortDateString()</h2>
    <br />
    <span>
        @Html.Label("Day")
        @Html.Label("Start Time")
        @Html.Label("End Time")
        @Html.Label("Operational")
    </span>
    @Html.DisplayFor(model => model.OplengthVm)
   
</div>
<div class="msc-overflow" style="height:225px;">
    @Html.HiddenFor(model => model.CDayID)
    @Html.HiddenFor(model => model.dtmDate)
    @Html.HiddenFor(model => model.intDay)
    @Html.HiddenFor(model => model.intMonth)
    @Html.HiddenFor(model => model.intYear)
    @Html.HiddenFor(model => model.intLessonsPerDay)
 
    <ul>
    @foreach (var studio in Model.lstStudios)
    {
        <li class="admin-day-li">
            <span class="studio-span">
                @Html.DisplayFor(modelItem => studio.strStudioName)
            </span>
            <input type="button" name="btnFolded" value="+"/>
            <table id="tblInstructorDay" class="msc-hidden">
                <tr>
                    <td>@Html.Label("Start Time")</td>
                    <td>@Html.Label("End Time")</td>
                    <td>@Html.Label("Slot Available")</td>
                </tr>
            @foreach (KeyValuePair<int, MusicSEC.ViewModels.CLessonVM> pair in studio.dctLessonSlots)
            {               
                 <tr data-instructorid="@pair.Value.CInstructorID">              
                    <td>@MusicSEC.Utility.CTimeUtility.ConvertToReadable(pair.Value.intStartTime)</td>
                    <td>@MusicSEC.Utility.CTimeUtility.ConvertToReadable(pair.Value.intEndTime)</td>
                    <td>@pair.Value.blnAvailable.ToString()</td>
                 </tr>
            } 
            </table>
        </li>
    }
    </ul>
</div>
<input type="hidden" id="hdnInstructId" value="@ViewBag.InstructorId" />
</div>
@Scripts.Render("~/bundles/jqueryval")
<script>
    //start unique variables
    var tr = $('#tblInstructorDay tr');
    var hdnInstructId = $('#hdnInstructId').val();
    //end unique

    $('input[name=btnFolded]').click(function () {
        var button = $(this);
        var val = (button.val() == '+') ? '-' : '+';
        button.parent().children('table').toggleClass('msc-hidden');
        button.val(val);
    });

    $('input[name=btnToggle]').click(function () {
        toggleDisplay();
    });


    // Unique
    $.each(tr, function (index, row) {
        var row = $(row);
        if (row.data('instructorid') == hdnInstructId) {
            var parent = row.parents('li');
            parent.children('.studio-span').addClass('msc-highlight');
            row.addClass('msc-highlight');
        }
    });
</script>

MusicSEC/Views/CDay/StudentDay.cshtml
@model MusicSEC.ViewModels.CDayVM
@using MusicSEC.ViewModels


@*@using (Ajax.BeginForm("UpdateDayTime", "CDay", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "AdminDay", OnComplete = "setActive" }))
{
*@
<div id="AdminDay">
<div>
    <input type="button" name="btnToggle" value="< Back" />
    <h2>@Model.dtmDate.ToShortDateString()</h2>
    <br />
    <span>
        @Html.Label("Day")
        @Html.Label("Start Time")
        @Html.Label("End Time")
        @Html.Label("Operational")
    </span>
    @Html.DisplayFor(model => model.OplengthVm)
   
</div>
<div class="msc-overflow" style="height:225px;">
    @Html.HiddenFor(model => model.CDayID)
    @Html.HiddenFor(model => model.dtmDate)
    @Html.HiddenFor(model => model.intDay)
    @Html.HiddenFor(model => model.intMonth)
    @Html.HiddenFor(model => model.intYear)
    @Html.HiddenFor(model => model.intLessonsPerDay)
 
    <ul>
    @foreach (var studio in Model.lstStudios)
    {
        <li class="admin-day-li">
            <span class="studio-span">
                @Html.DisplayFor(modelItem => studio.strStudioName)
            </span>
            <input type="button" name="btnFolded" value="+"/>
            <table id="tblStudentDay" class="msc-hidden">
                <tr>
                    <td>@Html.Label("Start Time")</td>
                    <td>@Html.Label("End Time")</td>
                    <td>@Html.Label("Slot Available")</td>
                </tr>
            @foreach (KeyValuePair<int, MusicSEC.ViewModels.CLessonVM> pair in studio.dctLessonSlots)
            {
                 <tr data-studentid="@pair.Value.CStudentID">
                    <td>@MusicSEC.Utility.CTimeUtility.ConvertToReadable(pair.Value.intStartTime)</td>
                    <td>@MusicSEC.Utility.CTimeUtility.ConvertToReadable(pair.Value.intEndTime)</td>
                    <td>@pair.Value.blnAvailable.ToString()</td>
                 </tr>
            } 
            </table>
        </li>
    }
    </ul>

</div>
<input type="hidden" id="hdnStudId" value="@ViewBag.StudentId" />
</div>
@*}*@
@Scripts.Render("~/bundles/jqueryval")
<script>
    //start unique variables
    var tr = $('#tblStudentDay tr');
    var hdnStudId = $('#hdnStudId').val();
    //end unique

    $('input[name=btnFolded]').click(function () {
        var button = $(this);
        var val = (button.val() == '+') ? '-' : '+';
        button.parent().children('table').toggleClass('msc-hidden');
        button.val(val);
    });

    $('input[name=btnToggle]').click(function () {
        toggleDisplay();
    });

    // Unique
    $.each(tr, function (index, row) {
        var row = $(row);
        if (row.data('studentid') == hdnStudId) {
            var parent = row.parents('li');
            parent.children('.studio-span').addClass('msc-highlight');
            row.addClass('msc-highlight');
        }
    });
</script>