MusicSEC/Models/CInstructor.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : CInstructor
// Abstract : Database Model for CIntstructors
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace MusicSEC.Models
{
    public class CInstructor 
    {
        public int CInstructorID { get; set; }
        public int intUserID { get; set; }

        [Display(Name = "First Name")]
        public string strFirstName { get; set; }

        [Display(Name = "Last Name")]
        public string strLastName { get; set; }

        [Display(Name = "Email Address")]
        public string strEmailAddress { get; set; }

        [Display(Name = "Phone Number")]
        public string strPhoneNumber { get; set; }

        [Display(Name = "Address")]
        public string strAddress { get; set; }

        [Display(Name = "City")]
        public string strCity { get; set; }

        [Display(Name = "State")]
        public int CStateID { get; set; }

        [Display(Name = "Zip Code")]
        public string strZipCode { get; set; }

        [Display(Name = "About")]
        public string strProfileDescription { get; set; }

        public int? CUserImageID { get; set; }

        public bool blnActive { get; set; }

        //Navigations
        public virtual CState State { get; set; }
        public virtual CUserImage ProfileImage { get; set; }
        public virtual ICollection<CStudent> Students { get; set; }
        public virtual ICollection<CLessonType> LessonTypes { get; set; }
    }
}

MusicSEC/Controllers/CInstructorController.cs
//---------------------------------------------------------------
// Author : Adam Shaver
// Class : CInstructorController
// Abstract : Controller for Instructors
//---------------------------------------------------------------

//---------------------------------------------------------------
// Imports
//---------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicSEC.DAL;
using MusicSEC.Models;
using System.Web.Security;
using MusicSEC.ViewModels;
using MusicSEC.Utility;

namespace MusicSEC.Controllers
{
    public class CInstructorController : Controller
    {
        private CUnitOfWork unit = new CUnitOfWork();

        //--------------------------------------------------------------
        // Name : InstructorProfile
        // Abstract : return the instructor profile view
        //--------------------------------------------------------------
        public ActionResult InstructorProfile(int instructorId = 0, bool blnIsPublic = true)
        {
            var instructor = unit.InstructorRep.FindById(instructorId);
  
            if (instructor == null)
            {
                ViewBag.States = new SelectList(unit.StateRep.GetAll(), "strStateName", "strStateName");
                ViewBag.intLessonTypeID = new SelectList(unit.LessonTypeRep.GetAll().OrderBy(x => x.strLessonType), "CLessonTypeID", "strLessonType");
                CInstructorVM instructorVM = new CInstructorVM();
                return PartialView("CreateInstructor", instructorVM);
            }

            return PartialView(new CInstructorVM().MapViewModel(unit, instructor.CInstructorID, 
                       (unit.IsAdministrator || unit.CurrentUserID == instructor.intUserID) ? false : true));
        }

        //--------------------------------------------------------------
        // Name : CreateInstructor
        // Abstract : return instructor view
        //--------------------------------------------------------------
        [HttpGet]
        public ActionResult CreateInstructor()
        {
            ViewBag.States = new SelectList(unit.StateRep.GetAll(), "strStateName", "strStateName");
            ViewBag.intLessonTypeID = new SelectList(unit.LessonTypeRep.GetAll().OrderBy(x => x.strLessonType), "CLessonTypeID", "strLessonType");
            CInstructorVM instructorVM = new CInstructorVM();
            return PartialView(instructorVM);
           // return View(instructorVM);
        }

        //--------------------------------------------------------------
        // Name : CreateInstructor POST
        // Abstract : create an instructor
        //--------------------------------------------------------------
        [Authorize(Roles = "Admin, Instructor")]
        [HttpPost]
        public ActionResult CreateInstructor(CInstructorVM cInstructorVM)
        {
            
            HttpPostedFileBase file = Request.Files[0];
            var instructor = cInstructorVM.MapModel(unit, cInstructorVM, file);
      //      var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToList();
            if (ModelState.IsValid)
            {
                instructor.intUserID = unit.CurrentUserID;
                unit.InstructorRep.Insert(instructor);
                bool worked = unit.Save();
            }
    //      return RedirectToAction("InstructorProfile", new { instructorId = instructor.CInstructorID });
            TempData["hdnDashMarker"] = "yes";
            return RedirectToAction("Dash", "Dashboard");
           
        }

        //--------------------------------------------------------------
        // Name : EditInstructor
        // Abstract : return edit view
        //--------------------------------------------------------------
        [HttpGet]
        public ActionResult EditInstructor(int id)
        {
            var instructorVM = new CInstructorVM().MapViewModel(unit, id, false);
            ViewBag.States = new SelectList(unit.StateRep.GetAll(), "strStateName", "strStateName");
            ViewBag.intLessonTypeID = new SelectList(unit.LessonTypeRep.GetAll().OrderBy(x => x.strLessonType), "CLessonTypeID", "strLessonType");
            return PartialView(instructorVM);
        }

        //--------------------------------------------------------------
        // Name : Edit Instructor Post
        // Abstract : save changes
        //--------------------------------------------------------------
        [HttpPost]
        public ActionResult EditInstructor(CInstructorVM cInstructorVM)
        {
            HttpPostedFileBase file = (Request.Files.Count > 0) ? Request.Files[0] : null;
            var instructor = cInstructorVM.MapModel(unit, cInstructorVM, file);
            unit.InstructorRep.Update(instructor);
            unit.Save();

            return RedirectToAction("InstructorProfile", new { instructorId = instructor.CInstructorID });
        }

        //--------------------------------------------------------------
        // Name : ManageInstructors
        // Abstract : Manage instructors for admin
        //--------------------------------------------------------------
        [HttpGet]
        public ActionResult ManageInstructors()
        {
            var lstInstructors = unit.InstructorRep.GetAll().
                                                    Select(x => new CInstructorVM().MapViewModel(unit, x.CInstructorID, false));

            return PartialView(lstInstructors);
        }

        //--------------------------------------------------------------
        // Name : InviteInstructor
        // Abstract : invite a new instructor to the academy
        //--------------------------------------------------------------
        public ActionResult InviteInstructor(string email)
        {
            if (email != "")
            {
                string strBusiness = unit.BusinessSettingsRep.GetAll().
                                                              Select(x => x.strBusinessName).
                                                              FirstOrDefault();

                // this works commented out to test just the email sending
                string[] astrUserInfo = CSeedUtility.SeedNewInstructor(strBusiness, email);
                bool blnSuccess = true;

                if (astrUserInfo[0] != null && astrUserInfo[0] != "" &&
                   astrUserInfo[1] != null && astrUserInfo[1] != "")
                {
                    blnSuccess = CEmailUtility.SendEmail(email, astrUserInfo[0], astrUserInfo[1], strBusiness);
                }
            }
            //TODO
            //Implement viewdata object to tell user if operation was completed successfully
            return RedirectToAction("ManageInstructors");
        }

        //--------------------------------------------------------------
        // Name : ProcessActiveInstructors
        // Abstract : set instructor to or from active status
        //--------------------------------------------------------------
        [HttpPost]
        public ActionResult ProcessActiveInstructors(string active, string inactive)
        {
            string[] astrActive = active.Split(',');
            string[] astrInActive = inactive.Split(',');
            UpdateActiveInstructors(astrActive, true);
            UpdateActiveInstructors(astrInActive, false);

            return RedirectToAction("ManageInstructors");
        }

        //--------------------------------------------------------------
        // Name : InstructorBrowser
        // Abstract : return all instructors in dialog browser
        //--------------------------------------------------------------
        public ActionResult InstructorBrowser()
        {
            var lstInstructors = unit.InstructorRep.GetAll().Select(x => new CInstructorVM().MapViewModel(unit, x.CInstructorID, true)).OrderBy(x => x.strLastName);
            return PartialView(lstInstructors);
        }

        //--------------------------------------------------------------
        // Name : InstructorAvailability
        // Abstract : return instructor availability view
        //--------------------------------------------------------------
        [HttpGet]
        public ActionResult InstructorAvailability(int instructorId = 0)
        {
            var availabilityVM = new InitialInstructorAvailVMList(unit, instructorId);
            return PartialView(availabilityVM);
        }

        //--------------------------------------------------------------
        // Name : InstructorAvailability
        // Abstract : save instructor availability
        //--------------------------------------------------------------
        [HttpPost]
        public ActionResult InstructorAvailability(string[] dayCode, string chkValues, string[] startTime )
        {
            string[] astrValues = chkValues.Split(',');

            int intInstructorId = SetAvailability(dayCode, astrValues, startTime);

            return RedirectToAction("InstructorAvailability", new { instructorId = intInstructorId });
        }

        //--------------------------------------------------------------
        // Name : UpdateActiveInstructors
        // Abstract : Update Instructors to Active status
        //--------------------------------------------------------------
        private void UpdateActiveInstructors(string[] instructorList, bool isActive)
        {
            bool blnActiveOpp = !isActive;

            for (int i = 0; i < instructorList.Length; i++)
            {
                int intInstructorId = (instructorList[i] != "") ? Convert.ToInt32(instructorList[i]) : - 1;
                if (unit.InstructorRep.GetAll().Any(x => x.CInstructorID == intInstructorId && x.blnActive == blnActiveOpp))
                {
                    var instructor = unit.InstructorRep.FindById(intInstructorId);

MusicSEC/Views/CInstructor/CreateInstructor.cshtml
@model MusicSEC.ViewModels.CInstructorVM
<style>
    .msc-instructor-create-container {
        height:350px;
        overflow-y:auto;
        overflow-x:hidden;
    }

        .msc-instructor-create-container select {
            width:310px;
        }

        .msc-instructor-create-container textarea {
            width:310px;
            height:75px;
        }
</style>
@using (Html.BeginForm("CreateInstructor", "CInstructor", new { enctype = "multipart/form-data" }, FormMethod.Post, new { id = "frmcreate" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true);
<div class="msc-instructor-create-container">
<div class="msc-dsp-table">
    <div class="msc-dsp-row">
        <div class="msc-dsp-cell">
            @Html.Action("UploadImage", "CUserImages", new { enableCaptions = false, enableButtonPane = false })
            @Html.DropDownList("LessonTypes", (SelectList)ViewBag.intLessonTypeID, "--Select Lesson Type--")
            <input type="button" name="btnAddLessonType" value="Add" />
            <input type="button" name="btnRemoveLessonType" value="Remove" />
            <!--ul to hold Lesson types-->
            <ul id="msc-ul" class="msc-ul">
            </ul>
            <input type="hidden" id="hdnLessonArray" name="strLessonTypeArray" />
        </div>
        <div class="msc-dsp-cell">
            <ul>
                <li>@Html.TextBoxFor(model => model.strFirstName, new { placeholder = "First Name" })</li>
                <li>@Html.TextBoxFor(model => model.strLastName, new { placeholder = "Last Name" })</li>
                <li>@Html.TextBoxFor(model => model.strEmailAddress, new { placeholder = "Email" })</li>
                <li>@Html.TextBoxFor(model => model.strPhoneNumber, new { placeholder = "Phone" })</li>
                <li>@Html.TextBoxFor(model => model.strAddress, new { placeholder = "Street Address" })</li>
                <li>@Html.TextBoxFor(model => model.strCity, new { placeholder = "City" })</li>
                <li>@Html.DropDownListFor(model => model.strState, (SelectList)ViewBag.States, "--Select State--")</li>
                <li>@Html.TextBoxFor(model => model.strZipCode, new { placeholder = "Zip" })</li>
            </ul>
            @Html.TextAreaFor(model => model.strProfileDescription, new { placeholder = "About" })
        </div>
    </div>
    <div class="msc-dsp-row">
        <div class="msc-dsp-cell">
            <input type="submit" value="Save" />
        </div>
    </div>
</div>
    <ul class="msc-profile-error-list">
    <li>@Html.ValidationMessageFor(model => model.strFirstName)</li>
    <li>@Html.ValidationMessageFor(model => model.strLastName)</li>
    <li>@Html.ValidationMessageFor(model => model.strEmailAddress)</li>
    <li>@Html.ValidationMessageFor(model => model.strPhoneNumber)</li>
    <li>@Html.ValidationMessageFor(model => model.strAddress)</li>
    <li>@Html.ValidationMessageFor(model => model.strCity)</li>
    <li>@Html.ValidationMessageFor(model => model.strState)</li>
    <li>@Html.ValidationMessageFor(model => model.strZipCode)</li>
    <li class="msc-right-align"><input type="button" id="btnErrorClose" value="Close" /></li>
</ul>
</div>
}


@Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/instructor-crud.js"></script>
<script src="~/Scripts/jmask-util.js"></script>
<script>
    var errorlist = $('.msc-profile-error-list');
    var btnErrorClose = $('#btnErrorClose');
    errorlist.hide();

    btnErrorClose.click(function () {
        errorlist.hide();
    });

    $('form').on('submit', function () {
        if (!$(this).valid()) {
            errorlist.show();
        }
    });
</script>

MusicSEC/Views/CInstructor/EditInstructor.cshtml
@model MusicSEC.ViewModels.CInstructorVM

@using(Html.BeginForm("EditInstructor", "CInstructor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true);


<div class="msc-profile-instructor-container">
    <div class="msc-profile-instructor-row">
        <div class="msc-dsp-cell" style="padding:10px;">
          
            <img id="imgUploadPreview" class="msc-profile-lg" src="@string.Format("data:image/{0}; base64, {1}",  Model.strFileType, Convert.ToBase64String(Model.bytImage))" />
            
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*" onchange="previewImage();" />
            @Html.DropDownList("LessonTypes", (SelectList)ViewBag.intLessonTypeID, "--Select Lesson Type--")
            <input type="button" name="btnAddLessonType" value="Add" />
            <input type="button" name="btnRemoveLessonType" value="Remove" />
            <!--ul to hold Lesson types-->
            <ul id="msc-ul" class="msc-ul">
                @foreach (var item in Model.lstLessonTypes)
                {
                    <li data-lessonid="@item.CLessonTypeID">@item.strLessonType</li>
                }
            </ul>
            <input type="hidden" id="hdnLessonArray" name="strLessonTypeArray" />
        </div>
        <div class="msc-dsp-cell">
            <ul>
                <li>@Html.TextBoxFor(model => model.strFirstName, new { placeholder = "First Name" })</li>
                <li>@Html.TextBoxFor(model => model.strLastName, new { placeholder = "Last Name" })</li>
                <li>@Html.TextBoxFor(model => model.strEmailAddress, new { placeholder = "Email" })</li>
                <li>@Html.TextBoxFor(model => model.strPhoneNumber, new { placeholder = "Phone" })</li>
                <li>@Html.TextBoxFor(model => model.strAddress, new { placeholder = "Street Address" })</li>
                <li>@Html.TextBoxFor(model => model.strCity, new { placeholder = "City" })</li>
                <li>@Html.DropDownListFor(model => model.strState, (SelectList)ViewBag.States, "--Select State--")</li>
                <li>@Html.TextBoxFor(model => model.strZipCode, new { placeholder = "Zip" })</li>
            </ul>
            @Html.TextAreaFor(model => model.strProfileDescription, new { placeholder = "About" })
            @Html.HiddenFor(model => model.CInstructorID)
            @Html.HiddenFor(model => model.CUserImageID)
        </div>
    </div>
    <div class="msc-dsp-row">
        <div class="msc-dsp-cell">
            <input type="submit" value="Save" />
            @Html.ActionLink("Cancel", "InstructorProfile", new { instructorId = Model.CInstructorID}, new { @class = "msc-color-link" })
        </div>
    </div>
</div>
}
<script src="~/Scripts/instructor-crud.js"></script>
<script src="~/Scripts/jmask-util.js"></script>

MusicSEC/Views/CInstructor/InstructorAvailability.cshtml
@model MusicSEC.ViewModels.InitialInstructorAvailVMList

@using(Html.BeginForm())
{
<div class="msc-avail-container">
<div class="msc-avail-row">    
    @foreach(var item in Model.lstAvailability)
    {
        <div class="msc-avail-cell">
            <span class="msc-center-align">@Html.DisplayFor(modelitem => item.strDayName)</span>
           @* @Html.DisplayFor(modelItem => item.strDayName)*@
            <ul class="msc-avail-ul">
                <li>
                    <span>@Html.DisplayName("Start Time")</span>
                    <span>@Html.DisplayName("End Time")</span>
                    <span>@Html.DisplayName("Available")</span>
                </li>
                @foreach(var avail in item.lstHelpers)
                {
                 
                    <li>
                        <span class="msc-left-align">@Html.DisplayFor(modelItem => avail.strStartTime)</span>
                        <span class="msc-right-align">@Html.DisplayFor(modelItem => avail.strEndTime)</span>
                        <span>@Html.CheckBoxFor(modelItem => avail.blnAvailable)</span>
                        <input type="hidden" name="dayCode" value="@item.intDayCode" />                      
                        <input type="hidden" name="startTime" value="@avail.intStartTime" />
                    </li>
                }
            </ul>
        </div> 
    }
</div>
<input type="submit" value="Save" />
<input type="hidden" name="chkValues" />  
</div>
}
<script>
    var processed = false;
    $('form').on('submit', function (e) {
        e.preventDefault();
        if (!processed) {
            var chks = $('input[type=checkbox]');
            var vals = '';
            $.each(chks, function (index, chk) {
                var chk = $(chk);
                vals += (chk.is(':checked')) ? chk.val() : '';
                vals += ',';
            });
            $('input[name=chkValues]').val(vals);
            processed = true;
        }
        $(this).submit();
    });
</script>

MusicSEC/Views/CInstructor/InstructorBrowser.cshtml
@model IEnumerable<MusicSEC.ViewModels.CInstructorVM>

<ul id="instructorList">
@foreach (var item in Model)
{
     <li class="msc-inst-br-item" data-id="@item.CInstructorID">
         @Html.DisplayFor(model => item)
     </li>
}
</ul>

<script>
    var instructorList = $('#instructorList');
    var currentInstructorID = 0;

    instructorList.children('li').click(function () {
        currentInstructorID = $(this).data('id');
        setHighlight();
    });

    function getID() {
        return currentInstructorID;
    };

    function setHighlight() {
        $.each(instructorList.children('li'), function (index, li) {
            var li = $(li);
            if (li.data('id') == currentInstructorID) {
                li.addClass('msc-highlight');
            }
            else {
                li.removeClass('msc-highlight');
            }
        });
    }


</script>

MusicSEC/Views/CInstructor/InstructorProfile.cshtml
@model MusicSEC.ViewModels.CInstructorVM


<div class="msc-profile-instructor-container">
    <div class="msc-profile-instructor-row">
        <div class="msc-dsp-cell">
            <img class="msc-mdm-img" src="@string.Format("data:image/{0}; base64, {1}",  Model.strFileType, Convert.ToBase64String(Model.bytImage))" />
            <ul>
                <li><label>What I teach</label></li>
                @foreach(var item in Model.lstLessonTypes)
                {
                    <li>@Html.DisplayFor(model => item.strLessonType)</li>
                }
            </ul>
        </div>   
        <div class="msc-dsp-cell">
            <ul>
                <li><label class="msc-label-for">Name : </label>@Html.DisplayFor(model => model.FullName)</li>
                <li><label class="msc-label-for">Email : </label>@Html.DisplayFor(model => model.strEmailAddress)</li>
                <li><label class="msc-label-for">Phone : </label>@Html.DisplayFor(model => model.strPhoneNumber)</li>
                @if(!Model.blnIsPublic)
                {
                    <li><label class="msc-label-for">Address : </label>@Html.DisplayFor(model => model.strAddress)</li>
                    <li><label class="msc-label-for">City : </label>@Html.DisplayFor(model => model.strCity)</li>
                    <li><label class="msc-label-for">State : </label>@Html.DisplayFor(model => model.strState)</li>
                    <li><label class="msc-label-for">Zip : </label>@Html.DisplayFor(model => model.strZipCode)</li>
                }
            </ul>
            @Html.TextAreaFor(model => model.strProfileDescription, new { id = "instructorProfileDescript", disabled = "disabled", @readonly = "readonly" })
        </div>
    </div>
    <div class="msc-dsp-row">
        <div class="msc-dsp-cell">
            @if(!Model.blnIsPublic)
            {
                @Html.ActionLink("Edit Profile", "EditInstructor", new { id = Model.CInstructorID }, new { @class = "msc-color-link" });
            }
        </div>
    </div>
</div>

MusicSEC/Views/CInstructor/InviteInstructor.cshtml
<style>
    #tblInvite {
        width:650px;
        padding:0px;
        margin-top:20px;
        margin-left:20px;
        height:40px;
    }
        #tblInvite tr {
            padding:0px;
            width:650px;
            display:block; 
            height:40px;
        }

            #tblInvite tr td {
                padding:0px;
                height:40px;
                display:inline-block;
            }

                #tblInvite tr td span {
                    display:inline-block;
                    width:auto;
                    height:40px;
                    width:500px;
                }
        #tblInvite input[type=email] {
            display:inline-block;
            margin:3px 0px 0px 0px;
            height:20px;
            border-bottom:2px inset black;
            width:350px;
        }
        #tblInvite input[type=button],  #tblInvite input[type=submit] {
           height:36px;
           margin-top:0px;
        }

    #tblInviteCell1 {
        width:125px;
    }

    #tblInviteCell2 {
        width:515px;
    }

    input[name=btnInviteSlide] {
        border-top-right-radius:0px;
        border-bottom-right-radius:0px;
        margin-right:0px;
    
    }

    .msc-slider input[type=submit] {
        border-top-left-radius:0px;
        border-bottom-left-radius:0px;
        margin-left:0px;
        vertical-align:top;
    }
</style>
@using(@Html.BeginForm("InviteInstructor","CInstructor", FormMethod.Post))
{
<table id="tblInvite">
    <tr>
        <td id="tblInviteCell1">
            <input type="button" name="btnInviteSlide" value="Invite" style="display:inline-block;" />
        </td>
        <td id="tblInviteCell2">
            <span class="msc-slider" >
                <input type="email" name="email" placeholder="instructor email" />
                <input type="submit" value="Send" />
            </span>
    </td>
    </tr>
</table>
}
<script>
    var btnSlide = $('input[name=btnInviteSlide]');
    var slider = $('.msc-slider');
    slider.hide();
    btnSlide.click(function () {
        slider.toggle('slide');
    });
</script>

MusicSEC/Views/CInstructor/ManageInstructors.cshtml
@model IEnumerable<MusicSEC.ViewModels.CInstructorVM>

@{
    ViewBag.Title = "Manage Instructors";

}

<div class="msc-mng-instruct-container">
    <span style="float:right;margin-top:15px;">
        <input type="text" id="txtActiveSearch" placeholder="search" />
        <input type="radio" name="rdActive" value="0" checked="checked" />
        <label>Active</label>
        <input type="radio" name="rdActive" value="1" />
        <label>Inactive</label>
    </span>
    @Html.Partial("../CInstructor/InviteInstructor")
  
<div class="msc-mng-instruct-row">   
    <div class="msc-dsp-cell">
        <h4>Active Instructors</h4>
        <ul id="sortable-one" class="msc-connected">
            @foreach (var item in Model)
            {
                if(Boolean.Parse(item.strActive))
                {
                    <li class="msc-div-table" title="Drag and drop to activate/deactivate instructors.">
                        @Html.DisplayFor(model => item)
                    </li> 
                }
            }
        </ul>
    </div>
    <div class="msc-dsp-cell">
        <h4>Inactive Instructors</h4>
        <ul id="sortable-two" class="msc-connected">
            @foreach (var item in Model)
            {
                if(!Boolean.Parse(item.strActive))
                {
                    <li class="msc-div-table"  title="Drag and drop to activate/deactivate instructors.">
                        @Html.DisplayFor(model => item)
                    </li> 
                }
            }
        </ul>
    </div>
</div>
    <p>
      <input type="button" id="btnUpdate" value="Update Changes" />
    </p>
</div>
<script src="~/Scripts/jmanage-entities.js"></script>
<script>
    function updateLists(activeList, inactiveList) {
        $.post('@Url.Action("ProcessActiveInstructors", "CInstructor")', { active: activeList, inactive: inactiveList });
    }
</script>
@*<script>
    var dirty = false;
    enableBtnUpdate(dirty);

    $(function () {
        $("#sortable-one, #sortable-two").sortable({
            connectWith: ".msc-connected",
            change: function () {
                dirty = true;
                enableBtnUpdate(dirty);
            }
        }).disableSelection();
    });

    $("#txtActiveSearch").keyup(function () {
        var active = $("input[name=rdActive]:checked").val();
        var sortableList = (active == 0) ? "#sortable-one li" : "#sortable-two li";

        $.each($(sortableList + " ul li"), function (index, li) {
            var li = $(li).children(".msc-name");
            if (li != null && li.text().trim().toUpperCase().match($("#txtActiveSearch").val().trim().toUpperCase())) {
                li.parents(sortableList).show();
            }
            else {
                li.parents(sortableList).hide();
            }            
        });
    });

    $("#btnUpdate").click(function () {
        var active = generateList("sortable-one");
        var inactive = generateList("sortable-two");
        updateInstructorLists(active, inactive);
    });

    function enableBtnUpdate(isDirty) {
        $("#btnUpdate").button({ disabled: !isDirty });
    };

    function generateList(selectorId) {
        var instructorList = "";
        $.each($("#" + selectorId + " li ul"), function (index, li) {
            var li = $(li);
            if (li.data("instructorid") != null) {
                instructorList += li.data("instructorid") + ",";
            }
        });
        return instructorList;
    };

    function updateInstructorLists(activeList, inactiveList) {
        $.post('@Url.Action("ProcessActiveInstructors", "CInstructor")', { active : activeList, inactive : inactiveList });
    }
</script>*@